### ISSUE TITLE
About face recognition dataset

### ISSUE THREAD

**Issue by SueeH** [polarisZhao/awesome-face#5]
Great conclusion for face recognition and detection！
I am confused about these dataset. Do you know MS-Celeb-1M and Trillion Pairs( MS-Celeb-1M-v1c & Asian-Celeb) have any relationship？  Is trillion pairs is part of MS-Celeb-1M(do some cleaning)？

**Comment by polarisZhao** [comment]
You can see some information for here:  http://trillionpairs.deepglint.com/overview
trillion pairs Datasets include training set and testing set:
**Training set**
MS-Celeb-1M-v1c with 86,876 ids/3,923,399 aligned images **cleaned** from MS-Celeb-1M dataset. This dataset has been excluded from both LFW and Asian-Celeb.
Asian-Celeb 93,979 ids/2,830,146 aligned images. This dataset has been **excluded from** both LFW and MS-Celeb-1M-v1c.
**Testing set**
Trillion Pairs
Trillion Pairs is consisted of the following two parts.
**ELFW:** Face images of celebrities in LFW name list. There are 274k images from 5.7k ids.
**DELFW:** Distractors for ELFW. There are in total 1.58 million face images from Flickr.

**Comment by sudhitpanchal** [comment]
Do you have the updated link for http://trillionpairs.deepglint.com/overview ?
